name: simply_poem
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.7.0
  firebase_storage: ^11.1.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  shared_preferences: ^2.1.0
  provider: ^6.1.2
  intl:
  image_picker:
  fluttertoast: ^8.0.9
  flutter_staggered_grid_view: ^0.4.0
  cloud_functions:
  flutter_svg: ^2.0.10+1
  intl_phone_number_input:
#  geocoding:
  location:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

